import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Photography",
  description: "Generated by Osezei using NextJs",
  openGraph: {
    title: "Photography",
    description: "Generated by Osezei using NextJs",
    url: "https://photogalleryvvv.vercel.app/",
    siteName: "Osezei",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
