import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BASE_URL } from "./api";
import { url } from "inspector";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  //metadataBase: new URL(BASE_URL),
  title: "Photography",
  description: "Generated by Osezei using NextJs",
  openGraph: {
    images: [
      {
        url: "http://localhost:3000/opengraph-image/opengraph-image",
        width: 1200,
        height: 630,
        alt: "gibberish",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
